### ISSUE TITLE
Files permissions prevent removing the arm-frosted-eabi directory

### ISSUE THREAD

**Issue by brabo** [insane-adding-machines/crosstool-ng#1]
In the arm-frosted-eabi directory a lot of files have permission 0444, preventing removal of the directory as normal user (sudo can be used to override).

**Comment by danielinux** [comment]
Hi @brabo can you verify if this is fixed in fc0930e2d9e7940694b3cc53587d468139d0ba68 ?
http://archive.trexotech.com:8081/arm-frosted-eabi-Jenkins-17.04.28_02.09.tar.bz2 <- should have the right permissions now.

cc: @ichigo663

**Comment by danielinux** [comment]
Verified by @brabo
